package in.capgemini.trainingtracker.modal;

import java.util.Date;

/**
 * This User modal is used to hold the data will travel layer to layer
 * @author hsraj
 *
 */
public class User {

	/**
	 * id of the user
	 * autogenerated
	 */
	private int id;
	/**
	 * name of the user
	 * it should be required
	 */
	private String name;
	/**
	 * email of the user
	 * it should be required
	 */
	private String email;
	/**
	 * name of the user
	 * it should be required
	 */
	private String loginid;
	/**
	 * password of the user
	 * it should be required
	 */
	private String password;
//	private Date createdAt;
	/**
	 * date at which user is created
	 */
	private String createdAt;
	/**
	 *  date at which user is created
	 */
	private Date updatedAt;
	/**
	 * @return id of the user
	 */
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getLoginid() {
		return loginid;
	}
	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
//	public Date getCreatedAt() {
//		return createdAt;
//	}
//	public void setCreatedAt(Date createdAt) {
//		this.createdAt = createdAt;
//	}
	public Date getUpdatedAt() {
		return updatedAt;
	}
	public String getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", email=" + email + ", loginid=" + loginid + ", password="
				+ password + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + "]";
	}
}
